---
# Source: bluecompute-ce/charts/orders/templates/mariadb_secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: orders-mariadb-secret
  labels:    
    app: "orders"
    tier: "backend"
    version: "v1"
    heritage: "Helm"
    release: "openshift"
    chart: orders-0.6.1
type: Opaque
data:
  mariadb-password: "cGFzc3dvcmQ="
