apiVersion: v1
entries:
  auth:
  - apiVersion: v1
    created: 2018-12-15T00:03:32.931693233+05:30
    description: A Helm chart for Kubernetes
    digest: 250e112cddaa38ba75279e44c712fd9099256c5ccdaa1504a65b6e796c9e2887
    home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
    name: auth
    sources:
    - https://github.com/ibm-cloud-architecture/refarch-cloudnative-auth/tree/microprofile
    urls:
    - auth-0.0.1.tgz
    version: 0.0.1
  catalog:
  - apiVersion: v1
    created: 2018-12-15T00:03:32.932379762+05:30
    description: A Helm chart for Kubernetes
    digest: d6b4892e561a8f2ddb2d076b5dbded433b97ce2327d421cf12acc3b833629f79
    home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
    name: catalog
    sources:
    - https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-inventory/tree/microprofile/catalog
    urls:
    - catalog-0.0.1.tgz
    version: 0.0.1
  customer:
  - apiVersion: v1
    created: 2018-12-15T00:03:32.932947685+05:30
    description: A Helm chart for Kubernetes
    digest: 24b0ea8322149dfe56b3fbfd0ff3024e7a8eed9ca642deb31ed557754c334cec
    home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
    name: customer
    sources:
    - https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-customer/tree/microprofile
    urls:
    - customer-0.0.1.tgz
    version: 0.0.1
  ibm-icpmonitoring:
  - created: 2018-12-15T00:03:32.936744802+05:30
    description: IBM monitoring service in private cloud
    digest: 2b872f58f2355c7d539eeb18a4ffaa252a83d074c9b41f45c03e58fdaf6e8edc
    engine: gotpl
    keywords:
    - IcpClusterResource
    - ICP
    - amd64
    - ppc64le
    - OpenSource
    name: ibm-icpmonitoring
    sources:
    - https://github.com/prometheus/prometheus
    - https://github.com/prometheus/alertmanager
    - https://github.com/prometheus/node_exporter
    - https://github.com/kubernetes/kube-state-metrics
    - https://github.com/grafana/grafana
    - https://github.com/prometheus/collectd_exporter
    - https://github.com/justwatchcom/elasticsearch_exporter
    tillerVersion: '>=2.7.0'
    urls:
    - ibm-icpmonitoring-1.1.0.tgz
    version: 1.1.0
  ibmcase-elasticsearch:
  - apiVersion: v1
    created: 2018-12-15T00:03:32.937463942+05:30
    description: ElasticSearch
    digest: 7e7ca3423c90f6c629ab2e17d2df0ec65f32c2ca29ceb54a4595a4464e03ea22
    home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
    icon: https://static-www.elastic.co/assets/blt9a26f88bfbd20eb5/icon-elasticsearch-bb.svg
    name: ibmcase-elasticsearch
    sources:
    - https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-inventory/tree/microprofile/catalog/chart/ibmcase-elasticsearch
    urls:
    - ibmcase-elasticsearch-0.0.1.tgz
    version: 0.0.1
  inventory:
  - apiVersion: v1
    created: 2018-12-15T00:03:32.939009852+05:30
    description: A Helm chart for Kubernetes
    digest: 9a07f2db6777f860d7ad0a0f0491785db0527a81a60dbf4a8a701408e7638a91
    home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
    name: inventory
    sources:
    - https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-inventory/tree/microprofile/inventory
    urls:
    - inventory-0.0.1.tgz
    version: 0.0.1
  keystore:
  - apiVersion: v1
    created: 2018-12-15T00:03:32.939640958+05:30
    description: A Helm chart for keystore
    digest: e1e2df1f8ec61cd64ee2f4cf7baa0a3ac931efe597f927026cf80e55fdcbba6d
    home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
    name: keystore
    sources:
    - https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile/Keystore
    urls:
    - keystore-0.0.2.tgz
    version: 0.0.2
  orders:
  - apiVersion: v1
    created: 2018-12-15T00:03:32.940378254+05:30
    description: BlueCompute Orders Microservice
    digest: fe90dbacf22ee5a1129ad41d8aa4ea8651a6df17412162c352c82f9bc2800ea7
    home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
    name: orders
    sources:
    - https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-orders/tree/microprofile
    urls:
    - orders-0.0.1.tgz
    version: 0.0.1
  web:
  - apiVersion: v1
    created: 2018-12-15T00:03:32.941175347+05:30
    description: BlueCompute Web BFF app
    digest: 32962aaec0632529896fcd2a8321e49b1ef48d6bc84127e9d08082297c643a2b
    home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
    name: web
    sources:
    - https://github.com/ibm-cloud-architecture/refarch-cloudnative-bluecompute-web/tree/microprofile
    urls:
    - web-0.0.1.tgz
    version: 0.0.1
  zipkin:
  - apiVersion: v1
    created: 2018-12-15T00:03:32.942232741+05:30
    description: A Helm chart for Zipkin
    digest: 0175ae6822858eee5a491773c292e4588b119bb963ba03029d607820d5321f09
    home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
    name: zipkin
    sources:
    - https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile/Zipkin
    urls:
    - zipkin-0.0.1.tgz
    version: 0.0.1
generated: 2018-12-15T00:03:32.929023394+05:30
