---
# Source: bluecompute-ce/charts/inventory/templates/mysql_secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: inventory-mysql-secret
  labels:    
    app: "inventory"
    tier: "backend"
    version: "v1"
    heritage: "Helm"
    release: "openshift"
    chart: inventory-0.6.0
type: Opaque
data:
  mysql-password: "cGFzc3dvcmQ="
