---
# Source: bluecompute-ce/charts/inventory/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: inventory
  namespace: bluecompute
  labels:    
    app: "inventory"
    tier: "backend"
    version: "v1"
    heritage: "Helm"
    release: "openshift"
    chart: inventory-0.6.0
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:    
    app: "inventory"
    tier: "backend"
    version: "v1"
    heritage: "Helm"
    release: "openshift"
    chart: inventory-0.6.0
