apiVersion: v1
entries:
  auth:
  - apiVersion: v1
    created: 2017-11-01T09:37:39.541057-05:00
    description: BlueCompute Auth Microservice
    digest: b90bd11009cd639fbb75a8a0818ce98af7b3054d0fd559a7ed9aaf59dd5eda14
    name: auth
    urls:
    - https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts/auth-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    created: 2017-11-01T09:37:39.540587-05:00
    description: BlueCompute Auth Microservice
    digest: 055b4ab2fad15d874622b02e36ec973c789cd16beffc3baab8e966951fa49123
    name: auth
    urls:
    - https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts/auth-0.1.0.tgz
    version: 0.1.0
  bluecompute-ce:
  - apiVersion: v1
    created: 2017-11-13T08:36:46.614963122-07:00
    description: Bluecompute Application Chart
    digest: f23647fb9829819ca7f27662acdad8891fc345323d49cd5597e643ffe6554afa
    name: bluecompute-ce
    urls:
    - https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts/bluecompute-ce/bluecompute-ce-0.0.2.tgz
    version: 0.0.2
  catalog:
  - apiVersion: v1
    created: 2017-11-01T09:37:39.547721-05:00
    description: BlueCompute Catalog Microservice
    digest: a7c4c551352b311144ee6da216d28a6aa55d74f53cd35288b5700fa736429406
    name: catalog
    urls:
    - https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts/catalog-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    created: 2017-11-01T09:37:39.547032-05:00
    description: BlueCompute Catalog Microservice
    digest: 5943bf174fa59f6bffafb011c2d35349324907c6c105e0b2f05dea39c59869c1
    name: catalog
    urls:
    - https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts/catalog-0.1.1.tgz
    version: 0.1.1
  customer:
  - apiVersion: v1
    created: 2017-11-01T09:37:39.549055-05:00
    description: BlueCompute Customer Microservice
    digest: 2c5efa1b721fce36d68913b37640b323b0e112110612279fb7a6dd26c01257bd
    name: customer
    urls:
    - https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts/customer-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    created: 2017-11-01T09:37:39.548252-05:00
    description: BlueCompute Customer Microservice
    digest: c637de164bd9267688eddd122476551f84712cf14f55f2f0681cb20770b70b5b
    name: customer
    urls:
    - https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts/customer-0.1.0.tgz
    version: 0.1.0
  grafana-bc:
  - created: 2017-11-01T09:37:39.549938-05:00
    description: The leading tool for querying and visualizing time series and metrics.
    digest: 41e9b7e0e2532428ac273edf9ef0e0980199cf097dd9b76a9239045752a5c040
    engine: gotpl
    home: https://grafana.net
    icon: https://raw.githubusercontent.com/grafana/grafana/master/public/img/logo_transparent_400x.png
    maintainers:
    - email: zanhsieh@gmail.com
      name: Ming Hsieh
    - email: brobert@il.ibm.com
      name: Robert Barron
    name: grafana-bc
    sources:
    - https://github.com/grafana/grafana
    urls:
    - https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts/grafana-bc-0.3.1.tgz
    version: 0.3.1
  ibmcase-bluemix-service:
  - apiVersion: v1
    created: 2017-11-01T09:37:39.550248-05:00
    description: Deploy a service in Bluemix and bind to my cluster
    digest: 7165656bb88cf6eb4e4ca945d11680dc7cad672234ba3d54bd9e29aca6124db8
    icon: http://www-05.ibm.com/il/gtu/img/BluemixLogo_172x203.png
    name: ibmcase-bluemix-service
    urls:
    - https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts/ibmcase-bluemix-service-0.1.0.tgz
    version: 0.1.0
  ibmcase-couchdb:
  - apiVersion: v1
    created: 2017-11-01T09:37:39.550597-05:00
    description: CouchDB
    digest: 915098959aacf3c0600e7b7270a27ee87912cb98ad11625c1866a9b8b4744535
    icon: http://couchdb.apache.org/image/couch@2x.png
    name: ibmcase-couchdb
    urls:
    - https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts/ibmcase-couchdb-0.1.0.tgz
    version: 0.1.0
  ibmcase-elasticsearch:
  - apiVersion: v1
    created: 2017-11-01T09:37:39.551904-05:00
    description: ElasticSearch
    digest: 1fe0b6a388523c0ddd06adf4747e3d1556e47b10239f4db82a4f4eb5384f5a2e
    icon: https://static-www.elastic.co/assets/blt9a26f88bfbd20eb5/icon-elasticsearch-bb.svg
    name: ibmcase-elasticsearch
    urls:
    - https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts/ibmcase-elasticsearch-0.1.1.tgz
    version: 0.1.1
  ibmcase-mysql:
  - apiVersion: v1
    created: 2017-11-01T09:37:39.552238-05:00
    description: Resilient MySQL deployment
    digest: 1d86b7df0cf578eca21dc46e0fd056344d1eb41572801097b3ae8dcefac12a4d
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Octicons-database.svg/200px-Octicons-database.svg.png
    name: ibmcase-mysql
    urls:
    - https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts/ibmcase-mysql-0.1.0.tgz
    version: 0.1.0
  inventory:
  - apiVersion: v1
    created: 2017-11-01T09:37:39.553562-05:00
    description: BlueCompute Inventory Microservice
    digest: 007979f85aacb5b822b01bcc4137be39d0ee26835c99d436160705f4e2101f60
    name: inventory
    urls:
    - https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts/inventory-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    created: 2017-11-01T09:37:39.552918-05:00
    description: BlueCompute Inventory Microservice
    digest: 27099b492c0de3ff363a2eafc79a823a14adf2f4ef1667ae7fad0b2b8287e1bf
    name: inventory
    urls:
    - https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts/inventory-0.1.1.tgz
    version: 0.1.1
  orders:
  - apiVersion: v1
    created: 2017-11-01T09:37:39.555167-05:00
    description: Bluecompute Orders Microservice
    digest: f7fe5f945a164da69c2d782f993fa95fd8f00d386a56c58369bb2fe6f7c3b637
    name: orders
    urls:
    - https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts/orders-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    created: 2017-11-01T09:37:39.55454-05:00
    description: Bluecompute Orders Microservice
    digest: e80032e4c5cd126bfe542f55fcf53994c1728a4b4b52336fa93198c20b02718b
    name: orders
    urls:
    - https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts/orders-0.1.0.tgz
    version: 0.1.0
  web:
  - apiVersion: v1
    created: 2017-11-01T09:37:39.555773-05:00
    description: BlueCompute Web BFF app
    digest: 31f11c627273cfe348904201001bdab124fad03a55552b17e3e79cb2213a99a9
    name: web
    urls:
    - https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts/web-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    created: 2017-11-01T09:37:39.555471-05:00
    description: BlueCompute Web BFF app
    digest: 578c75f83599b095fb0bd9e95034930442198c1e830dd4eea50c8cf62a460b15
    name: web
    urls:
    - https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts/web-0.1.0.tgz
    version: 0.1.0
generated: 2017-11-10T17:01:53.510429069-07:00
