apiVersion: v1
entries:
  bluecompute-ce:
  - apiVersion: v1
    created: 2019-04-23T17:05:53.911089-05:00
    description: Bluecompute Application Chart
    digest: 9ba5af500611071a5b00beea4a144b5168b0116d1ad978f3363521bf4acff57c
    name: bluecompute-ce
    urls:
    - https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/spring/docs/charts/bluecompute-ce/bluecompute-ce-0.0.9.tgz
    version: 0.0.9
  - apiVersion: v1
    created: 2019-04-23T17:05:53.906344-05:00
    description: Bluecompute Application Chart
    digest: 10240ca82b973ca0521827a6ba3434ada218e0a738f5c027163d5a17b94c866b
    name: bluecompute-ce
    urls:
    - https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/spring/docs/charts/bluecompute-ce/bluecompute-ce-0.0.8.tgz
    version: 0.0.8
  - apiVersion: v1
    created: 2019-04-23T17:05:53.901622-05:00
    description: Bluecompute Application Chart
    digest: a75b17096b5ba4a410cfb05479ea7ac08e2d9b1d0f58da55fea6edcad477f606
    name: bluecompute-ce
    urls:
    - https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/spring/docs/charts/bluecompute-ce/bluecompute-ce-0.0.6.tgz
    version: 0.0.6
generated: 2019-04-23T17:05:53.896749-05:00
