---
# Source: bluecompute-ce/charts/catalog/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  labels:
    app: "catalog"
    tier: "backend"
    version: "v1"
    heritage: "Helm"
    release: "openshift"
    chart: catalog-0.6.0
spec:
  selector:
    matchLabels:
      app: catalog
  replicas: 1
  template:
    metadata:
      labels:
        app: "catalog"
        tier: "backend"
        version: "v1"
        heritage: "Helm"
        release: "openshift"
        chart: catalog-0.6.0
    spec:
      initContainers:
      - name: test-elasticsearch
        image: alexeiled/curl:latest
        imagePullPolicy: IfNotPresent
        command:
        - "/bin/sh"
        - "-c"
        - "set -x; until curl -k ${ES_PROTOCOL}://${ES_HOST}:${ES_PORT}/${ES_HEALTH} | grep -E 'green|yellow'; do echo waiting for elasticsearch; sleep 1; done; echo elasticsearch is ready"
        resources:
          limits:
            memory: 384Mi
          requests:
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 2000
        env:
        - name: ES_URL
          value: "${ES_PROTOCOL}://${ES_HOST}:${ES_PORT}"
        - name: ES_HOST
          value: "catalog-elasticsearch-client"
        - name: ES_PROTOCOL
          value: "http"
        - name: ES_PORT
          value: "9200"
        - name: ES_HEALTH
          value: "_cat/health"
      - name: test-inventory
        image: alexeiled/curl:latest
        imagePullPolicy: IfNotPresent
        command:
        - "/bin/sh"
        - "-c"
        - "until curl ${INVENTORY_URL}; do echo waiting for inventory-service at ${INVENTORY_URL}; sleep 1; done; echo inventory is ready"
        resources:
          limits:
            memory: 384Mi
          requests:
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 2000
        env:
        - name: INVENTORY_URL
          value: http://inventory:8080
      containers:
      - name: "catalog"
        image: "ibmcase/bluecompute-catalog:0.6.0"
        imagePullPolicy: "Always"
        volumeMounts:
        - mountPath: /spring-tmp
          name: spring-tmp
        ports:
        - containerPort: 8081
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: 8091
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /health
            port: 8091
          initialDelaySeconds: 35
          periodSeconds: 20
          failureThreshold: 6
        resources:
          limits:
            memory: 384Mi
          requests:
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 2000
        env:
        - name: SERVICE_PORT
          value: "8081"
        - name: JAVA_TMP_DIR
          value: /spring-tmp
        - name: ES_URL
          value: "${ES_PROTOCOL}://${ES_HOST}:${ES_PORT}"
        - name: ES_HOST
          value: "catalog-elasticsearch-client"
        - name: ES_PROTOCOL
          value: "http"
        - name: ES_PORT
          value: "9200"
        - name: ES_HEALTH
          value: "_cat/health"
        - name: INVENTORY_URL
          value: http://inventory:8080
      volumes:
      - name: spring-tmp
        emptyDir:
          medium: "Memory"
