---
# Source: bluecompute-ce/charts/mysql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: inventory-mysql
  labels:
    app: inventory-mysql
    chart: "mysql-0.15.0"
    release: "openshift"
    heritage: "Helm"
type: Opaque
data:
  
  mysql-root-password:  "YWRtaW4xMjM="
  
  
  mysql-password:  "cGFzc3dvcmQ="
